# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: text_to_speech_api.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 0, "", "text_to_speech_api.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18text_to_speech_api.proto\x12\x03tts"-\n\rSpeechRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06gender\x18\x02 \x01(\t"\x1f\n\x0eSpeechResponse\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x32I\n\x0cTextToSpeech\x12\x39\n\x0eGenerateSpeech\x12\x12.tts.SpeechRequest\x1a\x13.tts.SpeechResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "text_to_speech_api_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SPEECHREQUEST"]._serialized_start = 33
    _globals["_SPEECHREQUEST"]._serialized_end = 78
    _globals["_SPEECHRESPONSE"]._serialized_start = 80
    _globals["_SPEECHRESPONSE"]._serialized_end = 111
    _globals["_TEXTTOSPEECH"]._serialized_start = 113
    _globals["_TEXTTOSPEECH"]._serialized_end = 186
# @@protoc_insertion_point(module_scope)
